server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_water_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.water.entity
  configuration:
    map-underscore-to-camel-case: true

mqtt:
  broker: tcp://localhost:1883
  client-id: campus-water-server
  username: admin
  password: $Slkh1628
  topics:
    # 后端与硬件  后端订阅主题
    subDispenser: subDispenser      # 订阅饮水机数据主题
    subIDCard: subIDCard            # 订阅饮水记录数据主题
    # 后端与前端  后端订阅主题
    pubNameData: pubNameData        # 订阅按姓名查询主题
    pubIdData: pubIDdata            # 订阅按ID查询主题

    # 后端与前端  后端发布主题
    subCar: subCard                 # 发布按姓名查询结果主题
    subRIDdata: subRIDdata          # 发布按ID查询结果主题